### PR TITLE
Modal styling

### PR DESCRIPTION
**Pull request by bhalt**
Removed HUD override CSS to default to ozp-bootstrap.

### CODE REVIEW

**Comment by bhalt** [comment]
@hoganmaps try again?

**Comment by hoganmaps** [comment]
k trying now

On Tue, Sep 29, 2015 at 3:02 PM, Bethany <notifications@github.com> wrote:

> @hoganmaps <https://github.com/hoganmaps> try again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ozone-development/ozp-hud/pull/132#issuecomment-144157540>
> .
>



-- 
Chris Hogan
@hoganmaps

**Comment by arw180** [comment]
:+1:

**Comment by hoganmaps** [comment]
it looks good with latest chrome and ie10. if the close button in the share folders modal is supposed to be slightly above the buttons, :+1:
screen shot 2015-10-06 at 10 49 34 am

**Comment by bhalt** [comment]
Yes, I believe that's coming from the standard ozp-bootstrap. I should adjust ozp-bootstrap later though, good catch.

**Pull request merged**
