### PR TITLE
Help modal styling

### PR DESCRIPTION
**Pull request by bhalt**
Clean up styling, layout, and language to maintain consistency on the Help Modal across the platform.

### CODE REVIEW

**Comment by clarkjefcoat** [comment]
Can you remove APP_TITLE from line 4 of helpmodal.jsx?

jshint gives a warning based on the changes you have made:
```
WARNING in ./app/js/components/NavBar/helpmodal.jsx
jshint results in errors
  'APP_TITLE' is defined but never used. @ line 4 char 35
    var { HELP_URL, HELPDESK_ADDRESS, APP_TITLE } = require('ozp-react-commons/OzoneConfig');
```

**Comment by bhalt** [comment]
Done - please review.

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by wski** [comment]
:+1:

**Pull request merged**
