### PR TITLE
Contacts modal

### PR DESCRIPTION
**Pull request by KageRyu7**
Removed 'Help' and 'Feedback' links in the Navbar and replaced them with a 'Contact' link to leads to a modal containing all forms of contact.

### CODE REVIEW

**Comment by wski** [comment]
Once rebased to one commit in correct format  `feat(Contact Modal): Added contact modal to global navbar` or similar it will be :+1:

**Comment by wski** [comment]
:+1:

**Comment by arw180** [comment]
I rebased this against the latest master (@wski upgrade to support node 0.12.7)

**Comment by arw180** [comment]
:+1:

**Pull request merged**
