### PR TITLE
feat(Shared Folders): Hud share folders to other people

### PR DESCRIPTION
**Pull request by wski**
@clarkjefcoat @tonyalletag 

Checkout my branch, start hud, and click the manate below.

[Foo](
http://localhost:8088/dist/#/add/New%20Folder/%22%5B%7B%5C%22id%5C%22:52,%5C%22entryid%5C%22:15%7D,%7B%5C%22id%5C%22:79,%5C%22entryid%5C%22:16%7D,%7B%5C%22id%5C%22:23,%5C%22entryid%5C%22:17%7D%5D%22)

it should add `Frame It 1`, `Clipboard 1` and `Chatterbox 1`. You need to be running on `ci-latest`. The shared link will be deponent on the backend a user is using.

It's worth noting this is kind of hacked in, backend changes will be required for a reliable method of doing this.

### CODE REVIEW

**Comment by tonyalletag** [comment]
:+1:

**Comment by wski** [comment]
See latest `Schrodinger's Tiles` commit @clarkjefcoat this should fix some of the goofyness of removing tiles of the same type. It also removes the "adding tiles..." text.

**Comment by clarkjefcoat** [comment]
Can you confirm which applications are added in this test?  They are not the ones in your original description.

Strange things happen if you already have bookmarked some of the items in the shared folder.

**Comment by wski** [comment]
The applications are different because the original code was not loading the correct ID's

It should be adding Airmail 2, Jotspot 4 and Breadbasket 7 from [this link]( http://localhost:8088/dist/#/add/New%20Folder/%22%5B%7B%5C%22id%5C%22:23%7D,%7B%5C%22id%5C%22:52%7D,%7B%5C%22id%5C%22:23%7D,%7B%5C%22id%5C%22:79%7D,%7B%5C%22id%5C%22:52%7D,%7B%5C%22id%5C%22:23%7D,%7B%5C%22id%5C%22:52%7D,%7B%5C%22id%5C%22:23%7D,%7B%5C%22id%5C%22:79%7D,%7B%5C%22id%5C%22:52%7D,%7B%5C%22id%5C%22:23%7D,%7B%5C%22id%5C%22:52%7D,%7B%5C%22id%5C%22:23%7D,%7B%5C%22id%5C%22:79%7D,%7B%5C%22id%5C%22:52%7D,%7B%5C%22id%5C%22:23%7D,%7B%5C%22id%5C%22:52%7D,%7B%5C%22id%5C%22:23%7D,%7B%5C%22id%5C%22:79%7D,%7B%5C%22id%5C%22:52%7D%5D%22)

that should also have fixed the crazyness

**Comment by clarkjefcoat** [comment]
The link in comment above puts 8 copies of Airmail 2, 8 copies of Jotspot 4 and 4 copies of Breadbasket 7 in a new folder.  Is that what you expected?

The change does appear to have "fixed the crazyness".

**Comment by wski** [comment]
Yeah that should be about right, i had many copies in the folder I was testing. To be sure you can create your own folder and share it with yourself

**Comment by clarkjefcoat** [comment]
:+1:

**Pull request merged**
