### PR TITLE
Folder sharing

### PR DESCRIPTION
**Pull request by hoganmaps**

### CODE REVIEW

**Comment by wski** [comment]
This isn't really something you did wrong, but can you add `npm-debug.log` to `.gitignore` other than that :+1:

**Comment by hoganmaps** [comment]
@clarkjefcoat or @arw180 pls review when you get a chance. preferably clark.

**Comment by clarkjefcoat** [comment]
Tooltip on "Get Shareable Link" looks different than other tooltips.
Folder name do not line up with other Apps Names in the HUD.

**Comment by hoganmaps** [comment]
@clarkjefcoat fixed?

**Comment by clarkjefcoat** [comment]
:+1:

**Pull request merged**
